name: "PR Title Checker"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          pattern: '^P2P-\d* - '